config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'home#index'

  resources :home, only: [:index, :show] do
    get :likes, on: :collection
    get :close, on: :collection
    get :open,  on: :collection
  end

  resources :users, onlu: :show do
    get :posts,  on: :member
    get :likes,  on: :member
    get :system, on: :member
  end

  resources :cards do
    get :open_modal,         on: :member
    get :close_modal,        on: :member
    get :create_like,        on: :member
    get :delete_like,        on: :member
    get :detail_create_like, on: :member
    get :detail_delete_like, on: :member
  end

  resources :likes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many_attached :images

  paginates_per 15

  CARD_GENRES = { 0 => 'Eat & Drink', 1 => 'See & Do', 2 => 'Events', 3 => 'Other' }

  def Card.genres(index)
    CARD_GENRES[index]
  end

  def Card.like_count(card_id)
    Card.find(card_id).likes.count
  end

  def Card.liked?(card_id, current_user)
    Like.find_by(card_id: card_id, user_id: current_user) ? true : false
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes
  has_many :cards
  has_many :like_cards, through: :likes, source: :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, except: [:open_modal, :close_modal]
  before_action :set_card, only: [:show, :edit, :open_modal, :close_modal, :create_like, :delete_like, :detail_create_like, :detail_delete_like]
  def new
    @card = Card.new
  end
  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  def show
  end
  def edit
    @card = Card.find(params[:id])
  end
  def update
    @card = Card.find(params[:id])
    @card.images.first.destroy if @card.images.first
    @card.update(card_params)
    redirect_to root_path
  end
  def destroy
    Card.find(params[:id]).destroy
    redirect_to posts_user_path(current_user)
  end
  def open_modal
  end
  def close_modal
  end
  def create_like
    current_user.likes.find_or_create_by(card_id: @card.id)
  end
  def delete_like
    Like.find_by(card_id: @card.id, user_id: current_user).destroy
  end
  def detail_create_like
    current_user.likes.find_or_create_by(card_id: @card.id)
  end
  def detail_delete_like
    Like.find_by(card_id: @card.id, user_id: current_user).destroy
  end

  private
    def card_params
      params.require(:card).permit(:title, :content, :genre_id, :user_id, :url, images: [])
    end
    def set_card
      @card = Card.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @card  = Card.new
    @q     = Card.all.ransack(params[:q])
    @cards = @q.result(distinct: true).page(params[:page])
  end

  def show
    @q     = Card.all.ransack(params[:q])
    @cards = Card.where(genre_id: params[:id]).page(params[:page])
    render 'index'
  end

  def likes
    @q     = Card.all.ransack(params[:q])
    @cards = @q.result(distinct: true).page(params[:page])
    render 'index'
  end

  def open
  end
  def close
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_check, only: :system
  def posts
    @post_cards = Card.where(user_id: current_user.id).page(params[:page])
  end

  def likes
    @like_cards = current_user.like_cards.page(params[:page])
  end

  def system
    @users = User.all
  end

  private

  def admin_check
    user = User.find(current_user.id)
    redirect_to root_path unless user.admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def card_genres
    [['Eat & Drink', 0], ['See & Do', 1], ['Events', 2], ['Other', 3]]
  end

  def modal_line_num(index)
    if    index <= 2
      '1'
    elsif index <= 5
      '2'
    elsif index <= 8
      '3'
    elsif index <= 11
      '4'
    elsif index <= 14
      '5'
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_detail-modal.html.erb
<div class="row">
  <div class="col-4 v-image-box-lg p-0">
    <% if card.images.attached? %>
      <%= image_tag(card.images.second ? card.images.second : card.images.first, class: 'visit-images') %>
    <% end %>
    <span class="rounded px-3 py-2 bg-white detail-like h5" id="detail-like-heart-<%= card.id %>">
      <%= Card.liked?(card.id, current_user) ? (render 'cards/detail_liked_heart', card: card) : (render 'cards/detail_like_heart', card: card) %>
    </span>
  </div>
  <div class="col-8 google-font p-2 px-4 detail-box">
    <div class="row">
      <div class="col-11 h3 mb-0 detail-title"><%= card.title %></div>
      <div class="col-1 h5 align-self-center"><%= link_to '', close_modal_card_path(card), remote: true, class: 'fas fa-times text-muted no-decorate' %></div>
      <div class="col-12 p text-muted mb-2"><%= Card.genres(card.genre_id) %></div>
      <div class="col-12 p detail-content mb-2"><%= card.content %></div>
      <div class="col-10 detail-website text-muted p bg-lighter w-100">Website: <%= link_to card.url, card.url, target: :_blank %></div>
      <% if current_user and card.user_id == current_user.id %>
        <div class="col-2 detail-edit-btn text-center"><%= link_to 'Edit', edit_card_path(card), class: 'text-dark far fa-edit' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/_detail_like_heart.html.erb
<%= link_to '',
            user_signed_in? ? detail_create_like_card_path(card) : open_home_index_path,
            method: :get,
            remote: true,
            class: 'far fa-heart liked'%>
&nbsp;
<%= Card.like_count(card.id) %>

app/views/cards/_detail_liked_heart.html.erb
<%= link_to '',
            user_signed_in? ? detail_delete_like_card_path(card) : open_home_index_path,
            method: :get,
            remote: true,
            class: 'fas fa-heart liked'%>
&nbsp;
<%= Card.like_count(card.id) %>

app/views/cards/_like_heart.html.erb
<%= link_to '',
            user_signed_in? ? create_like_card_path(card) : open_home_index_path,
            method: :get,
            remote: true,
            class: 'far fa-heart liked'%>
&nbsp;
<%= Card.like_count(card.id) %>

app/views/cards/_liked_heart.html.erb
<%= link_to '',
            user_signed_in? ? delete_like_card_path(card) : open_home_index_path,
            method: :get,
            remote: true,
            class: 'fas fa-heart liked'%>
&nbsp;<%= Card.like_count(card.id) %>

app/views/cards/close_modal.js.erb
$("#detail-modal-<%= @card.id %>").hide();
$(".like-heart").show();

app/views/cards/create_like.js.erb
$("#like-heart-<%= @card.id %>").html("<%= escape_javascript(render 'cards/liked_heart', card: @card) %>").show();

app/views/cards/delete_like.js.erb
$("#like-heart-<%= @card.id %>").html("<%= escape_javascript(render 'cards/like_heart', card: @card) %>").show();

app/views/cards/detail_create_like.js.erb
$("#detail-like-heart-<%= @card.id %>").html("<%= escape_javascript(render 'cards/detail_liked_heart', card: @card) %>").show();
$("#like-heart-<%= @card.id %>").html("<%= escape_javascript(render 'cards/liked_heart', card: @card) %>").show();

app/views/cards/detail_delete_like.js.erb
$("#detail-like-heart-<%= @card.id %>").html("<%= escape_javascript(render 'cards/detail_like_heart', card: @card) %>").show();
$("#like-heart-<%= @card.id %>").html("<%= escape_javascript(render 'cards/like_heart', card: @card) %>").show();

app/views/cards/edit.html.erb
<div class="row justify-content-center">
  <div class="col-10 h1 google-font text-center p-5 mt-3">
    Share good places you have visited!
  </div>
  <div class="col-8">
    <%= form_with model: @card, local: true do |form| %>
      <%= form.text_field :title, class: "form-control my-3", value: @card.title %>
      <%= form.file_field :images, multiple: true, accept: '.png, .jpg, .jpeg', class: '' %>
      <%= form.text_area :content, class: 'form-control my-3 new-post-content', value: @card.content %>
      <%= form.text_field :url, class: "form-control my-3", value: @card.url %>
      <%= form.select :genre_id, card_genres, {}, {selected: :first, class: "form-control custom-select d-block w-100"} %>
      <%= form.submit "Create!!", class: "btn btn-lg btn-info btn-block mt-4" %>
    <% end %>
  </div>
  <div class="col-8">
    <div class="row">
      <div class="col-4 offset-8 mt-3">
        <%= link_to 'Delete', card_path(@card), method: :delete,
                    class: 'btn btn-danger w-100',
                    data: { confirm: 'Are you sure you want to delete this ??' }
        %>
      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<div class="row justify-content-center">
  <div class="col-10 h1 google-font text-center p-5 mt-3">
    Share good places you have visited!
  </div>
  <div class="col-8">
    <%= form_with model: @card, local: true do |form| %>
      <%= form.text_field :title, class: "form-control my-3", placeholder: "title" %>
      <%= form.file_field :images, multiple: true, accept: '.png, .jpg, .jpeg', class: '' %>
      <%= form.text_area :content, class: 'form-control my-3 new-post-content', value: 'description' %>
      <%= form.text_field :url, class: "form-control my-3", placeholder: "URL" %>
      <%= form.select :genre_id, card_genres, {}, {selected: :first, class: "form-control custom-select d-block w-100"} %>
      <%= form.submit "Create!!", class: "btn btn-lg btn-info btn-block mt-4 mb-5" %>
    <% end %>
  </div>
</div>

app/views/cards/open_modal.js.erb
$(".detail-modal").hide();
$(".like-heart").show();
$("#like-heart-<%= @card.id %>").hide();
$("#detail-modal-<%= @card.id %>").html("<%= escape_javascript(render 'cards/detail-modal', card: @card) %>").fadeIn();

app/views/cards/show.html.erb
<div class="row">
  <div class="col-12 text-center">
    <% if @card.images.attached? %>
      <%= image_tag @card.images.first, class: 'image-show' %>
    <% end %>
  </div>
</div>

app/views/home/_cards_area.html.erb
<div class="col-4 v-image-box-lg p-0">
  <% if card.images.attached? %>
    <%= link_to image_tag(card.images.first, class: 'visit-images'),
                open_modal_card_path(card),
                remote:true
    %>
  <% end %>
  <% if current_user and card.user_id == current_user.id %>
    <div class="edit-btn"><%= link_to '', edit_card_path(card), class: 'h6 text-lighter far fa-edit' %></div>
  <% end %>
  <div class="v-image-text text-white w-100">
    <div class="h6 font-weight-bold">
      <%= card.title %>
    </div>
    <div class="row align-items-center">
      <div class="col p"><%= Card.genres(card.genre_id) %></div>
      <div class="col text-right mr-3 like-heart" id="like-heart-<%= card.id %>">
        <%= Card.liked?(card.id, current_user) ? (render 'cards/liked_heart', card: card) : (render 'cards/like_heart', card: card) %>
      </div>
    </div>
  </div>
</div>
<div class="col-12 detail-modal detail-modal-<%= modal_line_num(card_counter) %> bg-lighter" id="detail-modal-<%= card.id %>">
  <%= render 'cards/detail-modal', card: card %>
</div>

app/views/home/_need_login.html.erb
<div class="row justify-content-center align-items-center need-login-row">
  <div class="col-4 bg-white rounded px-4 py-2">
    <div class="row">
      <div class="col-11 h6 google-font pt-3 need-login-main">
        You need to log in first.
      </div>
      <div class="col-1 h5">
        <%= link_to '', close_home_index_path,
                    remote: true,
                    class: 'fas fa-times text-muted no-decorate' %>
      </div>
      <div class="col-12 text-center py-3">
        <%= link_to 'Log in', new_user_session_path, class: 'btn btn-primary w-25' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success w-25' %>
      </div>
    </div>
  </div>
</div>

app/views/home/_things2do.html.erb
<div class="row justify-content-center bg-white text-center py-4 pb-5">
  <div class="mx-5 rounded rounded-circle things-2-do">
    <%= link_to image_tag('/images/eat&drink.svg', class: 'things-2-do-svg p-3'), home_path(0) %>
    <div class="things-2-do-text">Eat & drink</div>
  </div>
  <div class="mx-5 rounded rounded-circle things-2-do">
    <%= link_to image_tag('/images/see&do.svg', class: 'things-2-do-svg p-3'), home_path(1) %>
    <div>See & do</div>
  </div>
  <div class="mx-5 rounded rounded-circle things-2-do">
    <%= link_to image_tag('/images/events.svg', class: 'things-2-do-svg p-3'), home_path(2) %>
    <div>Events</div>
  </div>
  <div class="mx-5 rounded rounded-circle things-2-do">
    <%= link_to image_tag('/images/other.svg', class: 'things-2-do-svg p-3'), home_path(3) %>
    <div>Other</div>
  </div>
  <div class="mx-5 rounded rounded-circle things-2-do">
    <%= link_to image_tag('/images/likes.svg', class: 'things-2-do-svg p-3'), likes_home_index_path %>
    <div>All</div>
  </div>
</div>

app/views/home/close.js.erb
$("#need-login").hide();

app/views/home/index.html.erb
<div class="row pt-3">
  <div class="col-sm-6 h1 google-font logo">VisitHub</div>
  <div class="col-12 welcome-text google-font text-center pt-4">Welcome to Osaka</div>
  <div class="col-12 h5 welcome-text-mini google-font text-center pb-3">The best experience for you. And share your best experience in Osaka for the next traveler.</div>
  <div class="col-12">
    <%= render 'home/things2do' %>
    <div class="row">
      <div class="col-12 p-3 bg-dark text-white">
        <%= search_form_for @q, url: root_path, class: '' do |f| %>
          <div class="row no-gutters form-group justify-content-center m-0">
            <div class="col-4 w-50">
              <%= f.search_field :title_or_content_cont_all, class: 'form-control form-control-sm rounded-0' %>
            </div>
            <div class="col-1">
              <%= button_tag :type => "submit", :class =>"btn btn-sm btn-default btn-s-md" do %>
                <i class="fa fa-search"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row modal-relative">
      <%= render partial: 'home/cards_area', collection: @cards, as: :card %>
    </div>
  </div>
  <div class="text-center google-font show-more mt-4">
    <%= paginate @cards %>
  </div>
</div>

app/views/home/open.js.erb
$("#need-login").html("<%= escape_javascript(render 'home/need_login') %>").fadeIn();

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <div class="row align-items-center">
    <div class="col-3 h1 google-font text-center text-white">
      VH
    </div>
    <div class="col-3 text-white">
      大阪府泉大津市池浦町<br>
      個人開発Webアプリケーション<br>
      【 VisitHub 】
    </div>
    <div class="col-3 text-white">
      Ikeura, Izumiotsu, Osaka, Japan<br>
      Personal development web application<br>
      【 VisitHub 】
    </div>
    <div class="col-3 p-5 text-white">
      <h6>CONTACT</h6>
      Email:<br>
      visithub411@gmail.com
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="row justify-content-end align-items-center">
  <% if user_signed_in? %>
    <div class="col-2 google-font text-left h4 m-0 pl-5"><%= link_to 'VH', root_path, class: 'text-white' %></div>
    <div class="col-4 offset-2 text-center">
        <%= link_to 'New post', new_card_path, class: 'new-post-btn btn btn-light border-0 mr-1' %>
        <%= link_to 'My page', posts_user_path(current_user), class: 'my-page-btn btn btn-light border-0 ml-1' %>
    </div>
    <div class="col-2 text-right header-email"><%= current_user.email if current_user %></div>
    <div class="col-2">
      <%= link_to 'Logout', destroy_user_session_path,
                  method: :delete,
                  class: 'text-white btn btn-outline-light',
                  data: { confirm: 'Logout OK ??' } if user_signed_in? %>
    </div>
  <% else %>
    <div class="col-2 google-font text-left h4 m-0 pl-5"><%= link_to 'VH', root_path, class: 'text-white' %></div>
    <div class="col-4 offset-2 text-center">
      <%= link_to 'New post', open_home_index_path, remote: true, class: 'new-post-btn btn btn-light border-0 mr-1' %>
      <%= link_to 'My page', open_home_index_path, remote: true, class: 'my-page-btn btn btn-light border-0 ml-1' %>
    </div>
    <div class="col-2 text-right header-email"><%= current_user.email if current_user %></div>
    <div class="col-2">
      <%= link_to 'Log in', new_user_session_path,
                  class: 'text-white btn btn-outline-light' %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VisitHub in Osaka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/header' %>
<!--    <p class="notice"><%#= notice %></p>-->
<!--    <p class="alert"><%#= alert %></p>-->
    <div class="top-bg-image"></div>
    <div class="need-login" id="need-login">
      <%= render 'home/need_login' %>
    </div>
    <div class="container p-0 mt-5">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_profile.html.erb
<div class="row justify-content-center bg-white text-center py-4 pb-5">
  <div class="col-12 h4 text-dark google-font py-2">
    Your Page
    <% if current_user.admin %>
<!--      <i class="fas fa-user-cog text-admin"></i>-->
      <%= link_to '', system_user_path(current_user), class: 'fas fa-user-cog text-admin' %>
    <% else %>
      <i class="fas fa-user text-user"></i>
    <% end %>
  </div>
  <div class="col-6 h6 google-font">
    Email: <%= current_user.email %>
  </div>
</div>

app/views/users/_system_users.html.erb
<div class="col-12">
  <div class="row text-center">
    <div class="col-2">
      <%= user.admin %>
    </div>
    <div class="col-4">
      <%= user.email %>
    </div>
    <div class="col-4">
      <%= user.created_at %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="row pt-3">
  <div class="col-12 mt-5">
    <%= render 'users/profile' %>
    <div class="row">
      <div class="col-6 p-0 bg-white">
        <div class="p-3 bg-lighter google-font h4 text-center m-0 user-posts-and-likes">
          <%= link_to "Your Posts (#{current_user.cards.count})", posts_user_path(current_user), class: 'text-dark' %>
        </div>
      </div>
      <div class="col-6 p-0 bg-white">
        <div class="p-3 bg-dark google-font h4 text-center m-0 user-posts-and-likes">
          <%= link_to "Your Likes (#{current_user.like_cards.count})", likes_user_path(current_user), class: 'text-white' %>
        </div>
      </div>
      <div class="col-12 p-3 bg-dark text-white google-font h4 text-center m-0">
      </div>
    </div>
    <div class="row modal-relative">
      <% if @like_cards.blank? %>
        <div class="col-12 no-post-nor-like text-white text-center pt-5">
          There are no liked posts yet.
        </div>
      <% else %>
        <%= render partial: 'home/cards_area', collection: @like_cards, as: :card %>
      <% end %>
    </div>
  </div>
  <div class="text-center google-font show-more mt-4">
    <%= paginate @like_cards %>
  </div>
</div>

app/views/users/posts.html.erb
<div class="row pt-3">
  <div class="col-12 mt-5">
    <%= render 'users/profile' %>
    <div class="row">
      <div class="col-6 p-0 bg-white">
        <div class="p-3 bg-dark google-font h4 text-center m-0 user-posts-and-likes">
          <%= link_to "Your Posts (#{current_user.cards.count})", posts_user_path(current_user), class: 'text-white' %>
        </div>
      </div>
      <div class="col-6 p-0 bg-white">
        <div class="p-3 bg-lighter google-font h4 text-center m-0 user-posts-and-likes">
          <%= link_to "Your Likes (#{current_user.like_cards.count})", likes_user_path(current_user), class: 'text-dark' %>
        </div>
      </div>
      <div class="col-12 p-3 bg-dark text-white google-font h4 text-center m-0">
      </div>
    </div>
    <div class="row modal-relative">
      <% if @post_cards.blank? %>
        <div class="col-12 no-post-nor-like text-white text-center pt-5">
          There are no your posts yet.
        </div>
      <% else %>
        <%= render partial: 'home/cards_area', collection: @post_cards, as: :card %>
      <% end %>
    </div>
  </div>
  <div class="text-center google-font show-more mt-4">
    <%= paginate @post_cards %>
  </div>
</div>

app/views/users/system.html.erb
<div class="row justify-content-center">
  <div class="col-8 p-5 bg-white mt-5">
    <div class="row">
      <%= render partial: 'users/system_users', collection: @users, as: :user %>
    </div>
  </div>
</div>